services:

  db:
    image: postgres:16
    container_name: app-prueba-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_prueba
      POSTGRES_USER: app_prueba
      POSTGRES_PASSWORD: app_prueba123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_prueba -d app_prueba"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: app-prueba-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app_prueba
      DB_USER: app_prueba
      DB_PASSWORD: app_prueba123
      JWT_SECRET: app_prueba_secret_123
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node src/seed.js && node src/server.js"

  frontend:
    build: ./frontend
    container_name: app-prueba-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data: